# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      #run: echo "Hello ${{ github.event.inputs.name }}"
      run: |
        echo $(id -u):$(id -g)
        cat /etc/passwd
        whoiam
