name: Build Browser Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Create folder for reports
          run: mkdir reports
        - name: Robot Framework Test
          # NOTE: joonvena/robotframework-docker-action@v0.1 had permissions issue
          # This action is based on a Docker image. I had to fall back to that image
          # and use --user flag
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${GITHUB_WORKSPACE}:/opt/robotframework/tests:Z \
              --user $(id -u):$(id -g) \
              -e BROWSER=chrome \
              ppodgorsek/robot-framework:latest
            
        - run: pwd
        #- run: $PWD
        - run: ls -lah
        - run: echo $GITHUB_WORKSPACE
        - run: ls -lah
          working-directory: reports
        - run: ls -lah
          working-directory: reports
        - run: |
            cd reports
            ls -lah
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: reports
            
    generate_report:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2
          with:
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}

            
